name: Bug report
description: Found a bug in Intersection? Report it here.
title: 'bug: '
labels:
  - bug
  - untriaged
body:
  - type: markdown
    attributes:
      value: >-
        # Hey there! Read me first!

        Thank you for putting your time into reporting a bug in Intersection! In
        order for us to best isolate and resolve your bug, please go through the
        following ste
  - type: checkboxes
    id: pre-checks
    attributes:
      label: Before we begin...
      description: Please confirm you've done the following.
      options:
        - label: I've checked the issue checker and ensured this is not a duplicate
          required: true
  - type: input
    id: intersection-version
    attributes:
      label: What's your version of Intersection?
      description: >-
        Please paste the output of Intersection's `/version` command below
        (excluding the Powered By section)
      placeholder: Intersection vX.Y.Z (git ...), compiled by ...
    validations:
      required: true
  - type: dropdown
    id: host-type
    attributes:
      label: How are you using Intersection?
      description: >-
        If you do not know what this means, you're probably using the "official
        hosted instance."
      options:
        - The official hosted instance
        - Someone else's public hosted instance
        - My own hosted instance
        - Locally, for development
    validations:
      required: true
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug you are experiencing.
      description: >-
        In a few concise sentences, please describe the bug. Please avoid simply
        saying "It didn't work."
      placeholder: Pressing this button doesn't cause this to happen!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Describe the steps needed to reproduce this bug.
      description: >-
        Provide a small list of steps that we can use to EXACTLY reproduce your
        bug.
      placeholder: 1. Run this command. 2. Press that button.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: >-
        Please describe the intended result. Please avoid the terms "it would
        work" etc.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      description: >-
        Please describe the actual result. Please avoid the terms "it didn't
        work" etc.
    validations:
      required: true
  - type: input
    id: search-terms
    attributes:
      label: Search Terms
      description: >-
        Please provide a few brief keywords that can be used to aid people
        searching for your issue
      placeholder: this-command that-button error-404
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Optionally, add any other useful context here.
  - type: markdown
    attributes:
      value: >-
        # Thank you!

        We appreciate your time and effort you have put into making this bug
        report. Please double-check everything and submit it!
